// Generate docs/playtest.md from the game's registries, so the coverage
// matrix tracks the code. Run: node scripts/playtest-doc.mjs  (or make playtest-doc)
import { writeFileSync, readFileSync } from 'node:fs';
import { SCENARIOS } from '../src/scenarios/index.js';
import { SKIES } from '../src/sky.js';
import { SCENERY } from '../src/scenery/index.js';
import { CHARACTERS } from '../src/characters.js';
import { LEVELS } from '../src/levels.js';
import { PLAYTEST_URL } from '../src/config.js';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const BASE = (process.env.BASE_URL ?? pkg.homepage ?? '/').replace(/\/?$/, '/');
const url = (q) => `${BASE}?${q}`;
const link = (q) => `[\`?${q}\`](${url(q)})`;

const hazards = Object.values(SCENARIOS).filter((s) => s.danger).map((s) => s.id);
const forceable = Object.keys(SCENARIOS).filter((k) => k !== 'finish');
const BLURB = {
  meadow: 'open strip, interstitial', grass: 'hunting maze with shelters, coins and eggs', road: 'cars, trucks, flatbeds; stallers at higher levels',
  river: 'logs, boats, subs, gators; divers', runway: 'planes taxiing, taking off, landing; ridable wings', rail: 'trains with ridable cars and crossing gates',
  freight: 'endless slow train, one gate always down; cross through open box cars or over flat cars',
  hedge: 'barrier: hedge wall, a tunnel under one cell', trees: 'barrier: touching canopies, one trunk missing', busStop: 'barrier: shelters and buses, one shelter with no back wall',
  picket: 'barrier: white pickets, one loose board (chicken hops any)', chainlink: 'barrier: chain-link run, a hole cut low (chicken hops any)', wall: 'barrier: brick wall, a culvert under one cell',
  mines: 'minesweeper field: mounds from the side, dots on safe cells, coins mark the path',
  maze: 'maze gauntlet: a Pac-Man board walled with the scenery, four vehicles hunting the corridors, weaknesses only the tilt shows, a bonus for every coin eaten',
};

const rows = [];
const table = (head, body) => `| ${head.join(' | ')} |\n| ${head.map(() => '---').join(' | ')} |\n${body.map((r) => `| ${r.join(' | ')} |`).join('\n')}\n`;

let md = `# Playtest URLs

Generated by \`make playtest-doc\` from the game's registries. Do not edit by hand.

Base: ${BASE}  
Playtest parameters are ${PLAYTEST_URL ? 'ON' : 'OFF'} in \`src/config.js\` (\`PLAYTEST_URL\`). When off, every parameter is ignored.

## Parameters

${table(['Parameter', 'Values', 'Effect'], [
  ['`start`', 'flag', 'Skip the title and coin slot, start with 4 lives'],
  ['`battle`', 'flag', 'Like `start`, then straight into the hearing at the Department of Pedestrian Grievances'],
  ['`hearing`', 'flag', 'Alias of `battle`'],
  ['`level`', '1–99', 'Start on this level'],
  ['`force`', forceable.map((k) => `\`${k}\``).join(' '), 'Every band on the board is this scenario'],
  ['`gauntlet`', hazards.map((k) => `\`${k}\``).join(' '), 'A gauntlet level of this hazard'],
  ['`sky`', Object.keys(SKIES).map((k) => `\`${k}\``).join(' '), "Override the level's sky"],
  ['`scenery`', Object.keys(SCENERY).map((k) => `\`${k}\``).join(' '), "Override the level's scenery theme"],
  ['`chars`', CHARACTERS.map((c) => `\`${c.id}\``).join(' '), 'Roster, comma separated; two ids gives co-op'],
  ['`coins`', '0–9999', 'Coin balance after start'],
  ['`lives`', '0–99', 'Lives after start'],
  ['`god`', 'flag', 'No deaths'],
  ['`debug`', 'flag', 'Open the debug panel'],
  ['`touch`', 'flag', 'Show the touch control bar'],
])}
Flags are present-or-absent. Without \`start\` the options are staged and apply when a coin is inserted.

## Levels

${table(['Level', 'Sky', 'Scenery', 'Danger bands', 'Hearing mix', 'Play'], LEVELS.map((l, i) => [
  String(i + 1), l.sky, l.scenery, String(l.bands), `air ${l.battle.air} · sea ${l.battle.sea} · land ${l.battle.land}`, link(`start&level=${i + 1}`),
]))}
Levels past ${LEVELS.length} repeat the table with rising difficulty: ${link(`start&level=${LEVELS.length + 1}`)}, ${link(`start&level=${LEVELS.length * 2}`)}.

## Scenarios

Each forced across the whole board, with god mode and a full pocket so nothing interrupts a look.

${table(['Scenario', 'What it exercises', 'Day', 'Night', 'High level'], forceable.map((k) => [
  `\`${k}\``, BLURB[k] ?? '', link(`start&force=${k}&god&coins=50`), link(`start&force=${k}&sky=night&god&coins=50`), link(`start&level=8&force=${k}&god&coins=50`),
]))}
## Gauntlets

${table(['Hazard', 'Play'], hazards.map((k) => [`\`${k}\``, link(`start&level=4&gauntlet=${k}`)]))}
## Skies and scenery

${table(['Sky', 'Level 1 board', 'Hearing'], Object.keys(SKIES).map((k) => [`\`${k}\``, link(`start&sky=${k}`), link(`battle&sky=${k}`)]))}
${table(['Scenery', 'Hunting maze in it'], Object.keys(SCENERY).map((k) => [`\`${k}\``, link(`start&force=grass&scenery=${k}&coins=30`)]))}
## Characters

${table(['Character', 'Perk', 'Tally ×', 'Solo', 'With a follower on the way'], CHARACTERS.map((c) => [
  `\`${c.id}\`${c.variants ? ` (variants: ${c.variants.join(', ')})` : ''}`,
  ['swims', 'fences', 'bushes', 'longJump', 'heavy', 'nineLives', 'honk'].filter((k) => c[k]).join(', ') || '—',
  (c.scoreMul ?? 1).toFixed(2), link(`start&chars=${c.id}`), link(`start&chars=${c.id}&force=grass&coins=30`),
]))}
Co-op: ${link(`start&chars=${CHARACTERS[0].id},${CHARACTERS[1].id}`)} · title with a pick staged: ${link(`chars=${CHARACTERS[CHARACTERS.length - 1].id}`)}

## Hearing

${table(['Case', 'Play'], [
  ['Level 1 mix', link('battle&level=1')], ['Night with headlights', link('battle&level=3')], ['High difficulty', link('battle&level=9')],
])}
## Economy and controls

${table(['Case', 'Play'], [
  ['Continue screen with coins to spend', link('start&lives=1&coins=60')],
  ['Game over with an empty pocket', link('start&lives=1&coins=0')],
  ['Peek budget only', link('start&coins=5')],
  ['Touch controls on a desktop', link('start&touch')],
  ['Debug panel open from the start', link('start&debug')],
])}
## Verifying from the shell

\`make smoke S=<scenario>\` and \`make shots\` drive the same builds headlessly; see \`scripts/smoke.mjs\` for the scenario list.
`;

writeFileSync(new URL('../docs/playtest.md', import.meta.url), md);
console.log(`wrote docs/playtest.md for ${BASE}`);
